// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: fvjeJAc2KXTwtdHurp6o8v
// Component: _ktPJwy9s9n
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import UploadAvatar from "../../UploadAvatar"; // plasmic-import: byu1aSvPCP/component
import TextInput from "../../TextInput"; // plasmic-import: A0Od_rnAuEc/component
import Button from "../../Button"; // plasmic-import: 3OB9jeYB3LR/component
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_chat_app.module.css"; // plasmic-import: fvjeJAc2KXTwtdHurp6o8v/projectcss
import sty from "./PlasmicUserProfile.module.css"; // plasmic-import: _ktPJwy9s9n/css

export const PlasmicUserProfile__VariantProps = new Array("isError");

export const PlasmicUserProfile__ArgProps = new Array("errorMessage");

function PlasmicUserProfile__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root,
        { [sty.rootisError]: hasVariant(variants, "isError", "isError") }
      )}
    >
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__m5
        )}
      >
        {"Update Profile"}
      </div>

      <UploadAvatar
        data-plasmic-name={"uploadAvatar"}
        data-plasmic-override={overrides.uploadAvatar}
        className={classNames("__wab_instance", sty.uploadAvatar)}
      />

      <TextInput
        data-plasmic-name={"firstNameInput"}
        data-plasmic-override={overrides.firstNameInput}
        className={classNames("__wab_instance", sty.firstNameInput)}
        placeholder={"Enter your first name"}
      />

      <TextInput
        data-plasmic-name={"lastNameInput"}
        data-plasmic-override={overrides.lastNameInput}
        className={classNames("__wab_instance", sty.lastNameInput)}
      />

      <Button
        data-plasmic-name={"saveProfileButton"}
        data-plasmic-override={overrides.saveProfileButton}
        className={classNames("__wab_instance", sty.saveProfileButton)}
        color={"softGreen"}
      >
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__oj3On
          )}
        >
          {"Save Profile"}
        </div>
      </Button>

      <Button
        data-plasmic-name={"button"}
        data-plasmic-override={overrides.button}
        className={classNames("__wab_instance", sty.button)}
        color={"link"}
        link={"/"}
      >
        {"Let's Chat!"}
      </Button>

      {(hasVariant(variants, "isError", "isError") ? true : true) ? (
        <div
          className={classNames(projectcss.all, sty.freeBox___9TwDy, {
            [sty.freeBoxisError___9TwDyU6YVt]: hasVariant(
              variants,
              "isError",
              "isError"
            )
          })}
        >
          <div
            className={classNames(projectcss.all, sty.freeBox___2GApt, {
              [sty.freeBoxisError___2GAptU6YVt]: hasVariant(
                variants,
                "isError",
                "isError"
              )
            })}
          >
            {p.renderPlasmicSlot({
              defaultContents: "Enter some text",
              value: args.errorMessage,
              className: classNames(sty.slotTargetErrorMessage, {
                [sty.slotTargetErrorMessageisError]: hasVariant(
                  variants,
                  "isError",
                  "isError"
                )
              })
            })}
          </div>
        </div>
      ) : null}
    </p.Stack>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "uploadAvatar",
    "firstNameInput",
    "lastNameInput",
    "saveProfileButton",
    "button"
  ],

  uploadAvatar: ["uploadAvatar"],
  firstNameInput: ["firstNameInput"],
  lastNameInput: ["lastNameInput"],
  saveProfileButton: ["saveProfileButton"],
  button: ["button"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicUserProfile__ArgProps,
      internalVariantPropNames: PlasmicUserProfile__VariantProps
    });

    return PlasmicUserProfile__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicUserProfile";
  } else {
    func.displayName = `PlasmicUserProfile.${nodeName}`;
  }
  return func;
}

export const PlasmicUserProfile = Object.assign(
  // Top-level PlasmicUserProfile renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    uploadAvatar: makeNodeComponent("uploadAvatar"),
    firstNameInput: makeNodeComponent("firstNameInput"),
    lastNameInput: makeNodeComponent("lastNameInput"),
    saveProfileButton: makeNodeComponent("saveProfileButton"),
    button: makeNodeComponent("button"),
    // Metadata about props expected for PlasmicUserProfile
    internalVariantProps: PlasmicUserProfile__VariantProps,
    internalArgProps: PlasmicUserProfile__ArgProps
  }
);

export default PlasmicUserProfile;
/* prettier-ignore-end */
