// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import { Router, useRouter } from "next/router";
import * as React from "react";
import { PlasmicHomepage } from "../components/plasmic/chat_app/PlasmicHomepage";
import enforceAuth from "../utils/enforceAuth";
import { supabase } from "../utils/supabaseClient";

function Homepage() {
    const router = useRouter();

    return <PlasmicHomepage />;
}

export const getServerSideProps = enforceAuth();
export default Homepage;
