// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PlasmicLogin } from "../components/plasmic/chat_app/PlasmicLogin";
import enforceUnAuth from "../utils/enforceUnAuth";

function Login() {
    return <PlasmicLogin />;
}

export const getServerSideProps = enforceUnAuth();
export default Login;
