// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PlasmicSignup } from "../components/plasmic/chat_app/PlasmicSignup";

function Signup() {
    return <PlasmicSignup />;
}

export default Signup;
